---
- name: Install OpenJDK
  become: yes
  apt:
    name: openjdk-11-jre-headless
    state: present

- name: Create OpenTripPlanner binary directory
  file:
    path: "{{ otp_bin_dir }}"
    mode: "0775"
    state: directory

- name: Store derived jarfile name for convenience
  set_fact:
    otp_jar_name: "otp-{{ otp_version }}{{ otp_jar_suffix }}.jar"

- name: Download OpenTripPlanner
  get_url:
    url: "https://repo1.maven.org/maven2/org/opentripplanner/otp/{{ otp_version }}/{{ otp_jar_name }}"
    dest: "{{ otp_bin_dir }}/{{ otp_jar_name }}"
    checksum: sha1:{{ otp_jar_sha1 }}
    mode: "0775"

- name: Create data directory
  become: yes
  file:
    path: "{{ otp_data_dir }}"
    mode: "0775"
    state: directory
    owner: "{{ otp_user }}"

- name: Copy json configuration
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ otp_data_dir }}"
    owner: "{{ otp_user }}"
  loop:
    - build-config.json
    - otp-config.json
    - router-config.json

- name: Install systemd service
  become: yes
  template:
    src: otp.service.j2
    dest: /etc/systemd/system/otp.service

- name: Enable OpenTripPlanner service
  become: yes
  systemd:
    name: otp.service
    enabled: yes
    daemon_reload: yes
