---
- hosts: all
  gather_facts: no
  remote_user: root
  roles:
    - common

- hosts: all
  become: yes
  roles:
    - geerlingguy.ntp
    - firewall

- hosts: all
  remote_user: zverik
  roles:
    - { role: opentripplanner, tags: otp }
    - { role: otp_data, tags: data }
    - { role: photon, tags: photon }
