---
- hosts: all
  gather_facts: no
  remote_user: root
  roles:
    - common

- hosts: all
  become: yes
  roles:
    - geerlingguy.ntp
    - geerlingguy.certbot
    - firewall

- hosts: all
  remote_user: zverik
  roles:
    - opentripplanner
    - otp_data
    - photon
