---
- hosts: all
  gather_facts: no
  become: yes
  remote_user: root
  roles:
    - common

- hosts: all
  become: yes
  remote_user: root
  roles:
    - role: oefenweb.swapfile
      swapfile_size: 1GB
    - geerlingguy.ntp
    - firewall

- hosts: all
  remote_user: zverik
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_ecdsa"
  roles:
    - opentripplanner
    - otp_data
    - photon
